# Generated by Django 5.0.1 on 2024-02-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_places_image_alter_places_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="places",
            name="image",
            field=models.ImageField(upload_to="homes/"),
        ),
    ]
