# Generated by Django 5.0.1 on 2024-02-13 19:46

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_places_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="places",
            name="image",
            field=models.ImageField(upload_to=home.models.image_upload),
        ),
    ]
