# Generated by Django 5.0.4 on 2024-04-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_places_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='continent',
            field=models.CharField(choices=[('Asia', 'Asia'), ('Africa', 'Africa'), ('Europe', 'Europe'), ('America', 'America')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='places',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='places',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='places',
            name='period',
            field=models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
