# Generated by Django 5.0.4 on 2024-04-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_places_continent_places_discount_places_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
