# Generated by Django 5.0.4 on 2024-05-01 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_places_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
