# Generated by Django 5.0.4 on 2024-05-01 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Book_trip', to='home.places'),
            preserve_default=False,
        ),
    ]
