# Generated by Django 5.0.4 on 2024-05-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_booking_email_booking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.ManyToManyField(to='home.places'),
        ),
    ]
